### ISSUE TITLE
Нестабильная работа поиска на некоторых платформах

### ISSUE THREAD

**Issue by mnbx-filatev** [diplodoc-platform/search-extension#12]
У ряда пользователей при статичной сборке, не работает должным образом поиск. 
При этом мне не удалось воспроизвести данный баг не удалось.

Либо падает в бесконечную загрузку
![image](https://github.com/user-attachments/assets/d654473d-d30b-460c-acf5-2ecd166088d7)

Либо падает в ошибку (без уточнений что было в консоли)
![image](https://github.com/user-attachments/assets/15f28bc3-c9ee-4e0f-a7c8-d2fe79cab95b)

Пользователям предлагали почистить кэш, но через какое-то время это появляться. Платформы на которых это возникает:

> Браузер Chrome
> Версия 130.0.6723.93
> macOS 14.6.1 (23G93)

На Windows, тоже такое случается:

> Браузер Chrome
> Версия 130.0.6723.119 
> Windows 10 22H2

Используемая версия при сборке: @diplodoc/cli - 4.49.0
Версия Nginx: nginx version: nginx/1.18.0 (Ubuntu)
Версия OS: Ubuntu 22.04.5 LTS
Метод сборки проекта: `yfm -i ./articles -o ./build/docs --static-content --allow-custom-resources`

.yfm
```yaml
allowHTML: true
addSystemMeta: true
resources:
  style:
    - _assets/styles/custom.css
  script:
    - _assets/mindbox.js 
    - _assets/intercom.js
search: true
```
